//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenGym.Domain.Entities
{
    using System;
    using ZenGym.Domain.Common;


    /// <summary>
    /// closing out the cash register 
    /// </summary>
    public partial class CachingUp : BaseEntity
    {
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal Collecting { get; set; }
        public decimal Disbursement { get; set; }
        public decimal Total { get; set; }
        public bool IsDeleted { get; set; }
    }
}
