//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenGym.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using ZenGym.Domain.Common;

    public partial class Member : BaseEntity
    {
        public Member()
        {
            this.Pointings = new HashSet<Pointing>();
            this.Subscriptions = new HashSet<Subscription>();
        }


        public string FisrtName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public DateTime? BirthDate { get; set; }
        public string BarCode { get; set; }
        public string PhotoLink { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }

        public DateTime? CertificationDate { get; set; }
        public decimal? Size { get; set; }
        public decimal? Weight { get; set; }
        public decimal? IMC { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }


        public int? TeamId { get; set; }
        public virtual Team Team { get; set; }

        public virtual ICollection<Pointing> Pointings { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
