//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenGym.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using ZenGym.Domain.Common;

    public partial class Pointing : BaseEntity
    {

        public DateTime EntryTime { get; set; }
        public DateTime ExitTime { get; set; }


        public int MemberId { get; set; }
        public virtual Member Member { get; set; }

        public int SubscriptionId { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
