//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenGym.Domain.Entities
{
    using System;
    using System.Collections.Generic;
        using ZenGym.Domain.Common;

    public partial class Product : BaseEntity
    {
        public Product()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public string Designation { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal BuyingPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
