//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenGym.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using ZenGym.Domain.Common;
    using ZenGym.Domain.Entities.Model;

    public partial class Sale : BaseEntity
    {
        public Sale()
        {
            this.SellItems = new HashSet<SellItem>();
        }
        public string Client { get; set; }
        public decimal Total { get; set; }
        public string IsDeteted { get; set; }

        public virtual ICollection<SellItem> SellItems { get; set; }
    }
}
