//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenGym.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using ZenGym.Domain.Common;

    public partial class Subscription : BaseEntity
    {
        public Subscription()
        {
            this.Pointings = new HashSet<Pointing>();
        }
        public int Duration { get; set; }
        public decimal Amount { get; set; }
        public DateTime StartingDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal ReceivedAmount { get; set; }
        public decimal RemainingAmount { get; set; }
        public bool IsCanceled { get; set; }

        public int SubscriptionTypeId { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }

        public int MemberId { get; set; }
        public virtual Member Member { get; set; }

        public virtual ICollection<Pointing> Pointings { get; set; }
    }
}
