//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenGym.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using ZenGym.Domain.Common;

    public partial class Team : BaseEntity
    {
        public Team()
        {
            this.Members = new HashSet<Member>();
        }

        public string Libelle { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<Member> Members { get; set; }
    }
}
